version: '3.5'

services:
#====================NGINX====================
  nginx:
    image: daolamsoncntt/nginx-node:8
    ports:
      - 6060:80
    volumes:
      - ./config/000-default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html/
    depends_on:
      - php_fpm
    restart: always

#====================PHP FPM====================
  php_fpm:
    image: daolamsoncntt/php:7.2
    depends_on:
      - db_mysql
      - db_redis
    volumes:
      - /root/www/data/mysql:/var/www/html/
    restart: always

#====================SUPERVISOR====================
  # supervisor:
  #   image: daolamsoncntt/supervisor:${VERSION_PHP}
  #   depends_on:
  #     - db_mysql
  #     - db_redis
  #   volumes:
  #     - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
  #     - ${PATH_API}:/var/www/html/
  #   command: bash -c "service supervisor start && php-fpm"
  #   restart: always

#====================MYSQL====================
  db_mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_blog
    volumes:
      - ../storage/data/mysql:/var/lib/mysql
    restart: always

#====================REDIS====================
  db_redis:
    image: redis:latest
    ports:
      - 63791:6379   
    restart: always
