version: '3.5'

networks:
  busrental_network:
    driver: bridge

services:
#====================NGINX====================
  nginx:
    image: daolamsoncntt/nginx-node:8
    ports:
      - ${PORT_HAVAZ}:80
    volumes:
      - ./config/000-default.conf:/etc/nginx/conf.d/default.conf
      - ${PATH_API}:/var/www/html/
    depends_on:
      - php_fpm
    networks:       
      - busrental_network     
    restart: always

#====================PHP FPM====================
  php_fpm:
    image: daolamsoncntt/php:${VERSION_PHP}
    depends_on:
      - db_mysql
      - db_redis
    volumes:
      - ${PATH_API}:/var/www/html/
    networks:       
     - busrental_network
    restart: always

#====================SUPERVISOR====================
  # supervisor:
  #   image: daolamsoncntt/supervisor:${VERSION_PHP}
  #   depends_on:
  #     - db_mysql
  #     - db_redis
  #   volumes:
  #     - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
  #     - ${PATH_API}:/var/www/html/
  #   networks:       
  #     - busrental_network
  #   command: bash -c "service supervisor start && php-fpm"
  #   restart: always

#====================MYSQL====================
  db_mysql:
    image: mysql:${VERSION_MYSQL}
    ports:
      - ${PORT_MYSQL}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_blog
    volumes:
      - ${PATH_MYSQL}:/var/lib/mysql
    networks:       
      - busrental_network
    restart: always

#====================REDIS====================
  db_redis:
    image: redis:latest
    ports:
      - ${PORT_REDIS}:6379
    networks:       
      - busrental_network     
    restart: always
